version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle
      restart: unless-stopped
    volumes:
      - /opt/oracle:/opt/oracle/oradata
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      TZ: Asia/Tehran
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: password
      ORACLE_EDITION: enterprise
      ORACLE_CHARACTERSET: AL32UTF8
      ENABLE_ARCHIVELOG: false
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: 4.000

