version: "3.4"
secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
  DB_ROOT_PWD:
    file: .secrets/db_root_pwd.txt

services:
  shalgham:
    image: site.com/shalgham:4.1.1
    container_name: shalgham1
    restart: unless-stopped
    command: start-dev
    network_mode: host
    user: 0:0
    networks:
      - clusterNet
    environment:
      - DBADDRESS=db
      - DBGADDRESS=dbg
    depends_on:
      - redis
    ports:
      - 8099:8099
      - 127.0.0.1:8099:8099/udp
    volumes:
      - "/path/to/a:/path/to/b"
      - "/path/to/a:/path/to/b:Z"
      - "/path/to/a:/path/to/b:ro"
    extra_hosts:
      - "a.a.com:1.1.1.1"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_TIME
      - SYS_NICE
    sysctls:
      - 'net.ipv4.conf.all.src_valid_mark=1'
      - 'net.ipv4.ip_forward=1'
    deploy:
      mode: replicated
      #mode: global
      replicas: 1
      resources:
        limits:
          memory: 8G
          cpus: 4.000
      placement:
        constraints: [node.role == manager]
        #constraints: [node.platform.os == linux]
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        window: 60s

networks:
  zeebe_network:
    driver: bridge
  agent_network:
    driver: overlay
    attachable: true
  clusterNet:
    external:
      name: clusterNet

volumes:
  portainer_data:
  zeebe0:
  zeebe1:
  zeebe2:
