version: "3.4"
services:
  3xui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3xui
    restart: unless-stopped
    network_mode: host
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
    depends_on:
      - redis
    volumes:
      - "/opt/3xui/db/:/etc/x-ui/"
      - "/opt/3xui/cert/:/root/cert/"
