services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.4.5-noble
    restart: unless-stopped
    environment:
      TZ: 'Asia/Tehran'
      MARIADB_ROOT_PASSWORD: 'password'
      MARIADB_USER: zabbix
      MARIADB_PASSSWORD: zabbix-password
      MARIADB_DATABASE: zabbix
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - /opt/zabbix/mariadb:/var/lib/mysql:Z

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:7.0-alpine-latest
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      TZ: 'Asia/Tehran'
      DB_SERVER_HOST: mariadb
      DB_SERVER_PORT: 3306
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix-password'
      MYSQL_DATABASE: 'zabbix'
    ports:
      - 10051:10051
    volumes:
      - /opt/zabbix/zabbix-server:/var/lib/zabbix:Z

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:7.0-alpine-latest
    restart: unless-stopped
    depends_on: 
      - zabbix-server
    environment:
      TZ: 'Aria/Tehran'
      DB_SERVER_HOST: mariadb
      DB_SERVER_PORT: 3306
      MYSQL_USER: 'zabbix'
      MYSQL_PASSWORD: 'zabbix-password'
      MYSQL_DATABASE: 'zabbix'
      PHP_TZ: 'Asia/Tehran'
      ZBX_SERVER_HOST: 'zabbix-server'
    ports:
      - 80:8080

  zabbix-snmptraps:
    container_name: zabbix-snmptraps
    image: zabbix/zabbix-snmptraps:7.0-alpine-latest
    restart: unless-stopped
    depends_on:
      - zabbix-server
    ports:
      - 162:1162/udp
    volumes:
      - /opt/zabbix/mibs:/usr/share/snmp/mibs:ro
      - /opt/zabbix/zabbix-server/snmptraps:/var/lib/zabbix/snmptraps:rw

