services:
  rocketchat:
    image: rocket.chat:8.2.0
    container_name: rocketchat
    restart: unless-stopped
    labels:
      traefik.enable: "false"
    environment:
      REG_TOKEN: ''
      ROOT_URL: 'http://localhost'
      MONGO_URL: 'mongodb://rocket:rocket@1.1.1.1:27017/rocket'
    ports:
      - "3000:3000"
      
