services:
  app:
    image: jc21/nginx-proxy-manager:2.12.3
    restart: unless-stopped
    environment:
      TZ: 'Asia/Tehran'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /opt/nginxreverseproxy/data:/data
      - /opt/nginxreverseproxy/letsencrypt:/etc/letsencrypt
