version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Tehran
      REDIS_PORT: 6379
      REDIS_DATABASES: 15

