version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: '--requirepass passwd'
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Tehran
      REDIS_PORT: 6379
      REDIS_DATABASES: 15
    volumes:
      - /opt/docker/redis:/data

  redisinsight:
    container_name: redisinsight
    user: 0:0
    image: redis/redisinsight:2.70.1
    ports:
      - 127.0.0.1:5540:5540
    volumes:
      - /opt/docker/redisinsight/:/data
